---
steps:
  - name: gcr.io/cloud-builders/docker
    id: Pull
    entrypoint: bash
    args:
      - -c
      - |
        docker pull gcr.io/$PROJECT_ID/$_IMAGE:latest || exit 0
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA
      - --cache-from
      - gcr.io/$PROJECT_ID/$_IMAGE:latest
      - .
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA
  - name: gcr.io/cloud-builders/gcloud
    id: Set image name
    entrypoint: /bin/sh
    args:
      - -c
      - >
        sed -i "s/image: IMAGE/image: gcr.io\/$PROJECT_ID\/$_IMAGE:$SHORT_SHA/g"
        k8s/deployment.yaml
  - name: gcr.io/cloud-builders/gcloud
    id: Authenticate kubernetes
    args:
      - container
      - clusters
      - get-credentials
      - $_CLUSTER
      - --zone
      - $_ZONE
  - name: gcr.io/cloud-builders/kubectl
    id: Deploy
    args:
      - apply
      - -f
      - k8s/
  - name: gcr.io/cloud-builders/gcloud
    id: Tag
    args:
      - container
      - images
      - add-tag
      - gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA
      - gcr.io/$PROJECT_ID/$_IMAGE:latest
