---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-tutorial-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: gke-tutorial-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: gke-tutorial-deployment
        env: production
    spec:
      containers:
        - name: gke-tutorial-deployment
          image: IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: LOG_LEVEL
              value: info
            - name: NODE_ENV
              value: production
