apiVersion: v1
kind: Service
metadata:
  name: gke-tutorial-deployment
spec:
  selector:
    app: gke-tutorial-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
